name: Build JP 6.0 

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches: ['**']

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: setup workspace
      run: yes | ./setup_workspace.sh 6.0
    - name: apply patches
      run: git config --global user.email "builder@example.com" && git config --global user.name "builder" && ./apply_patches.sh apply 6.0
    - name: build
      run: ./build_all.sh 6.0
